dist: xenial
script:
  - mkdir releases
  - touch releases/test
deploy:
  provider: releases
  api_key:
    secure: a9ZFKx88VVrsNSHd5622EjaQtdd8Ml7jWl0e4SSfBMbmlx21L4nbSfJjfTQCz6ghQpaRtKvfCwkmF7IIdLYfl+prkzgOlCoAkVTOkgqvX0hfI58wG0Qw62M5Lqr6NCtwWTcTJu72OQhhnVkEjOhUEZT+Ai9U3CTFWY5JC5qBhgzgN1PRbuzDkRZaUM6VGXz2HfzIrqkQWk6F1GOUwSsMqEMm7QUD8E7N9HVUf6RkNSjQY1dvA2qyeh7FWnK2FT50PSNT7xaN8sa35+2rxRh7qwSCbaB+YPQ8wrKamsNznrruMIPxZMKbfMNtU9U4vcMZ/fs5EfrGnjZUdq2LjO12Tq/JETX5Iw44Ha8T06J7gG02qX+sAI0Egnb9JcTLg8C04ZGTyVImM4bTNW8WJuOEgB91G2eZTmtdayjEdxMkc4tWRLOZHl8zCAc5FDbuqC2iaSZbSviXJykgEAvqJO4cdh6f3q4fL7mR+yaw4CrYuv5YOD39MjGzxCcBqY/9BuuNvdbQAHMRnsInayzdM3K1r9jrzPbVI1hH8gkKCcYSfiiXgG5+034FVbIxmAdAf586XamEihJR8izLpphjIQDfawTAyDIFvvzZgZWBUQ0LriQoNZxR3wE9Q1YfDiwkhxkP8K9k2RTDKubxRd3NSygOQjPAlLqPT5sl5Iz/KCqiJ4s=
  file: releases/*
  on:
    repo: tamuhey/test
